### ISSUE TITLE
stenoread errors out due to certificate issues

### ISSUE THREAD

**Issue by jeffgeiger** [rocknsm/rock#2] opened 2015-12-23 22:27 UTC
Temp workaround is (possibly) to add a "-k" to the curl syntax.  Cert handling/generation upstream may need adjusted to permanently fix.

**Comment by dcode** [comment] 2016-01-03 07:19
Need to figure out the root cause for this. This didn't happen when the package was created (I don't think), so I'm thinking it was an OpenSSL upgrade?

 - [ ] Need to confirm vs. upstream fresh build (a simple package rebuild would be easy)
 - [ ] See if there's some weird cert validation issue in the cert types. I've already looked into this a bit, but it isn't clear to me. The certs looks like they have the right roles.

**Comment by jeffgeiger** [comment] 2016-02-29 05:22
This can be alleviated by adding `-k` or `--insecure` to the default curl syntax in stenocurl.  Need to fix it via PR upstream or monkey patch it with chef.

**Comment by gconnell** [comment] 2016-04-28 23:32
@dcode: did this get fixed with https://github.com/google/stenographer/issues/124

**Comment by dcode** [comment] 2017-02-14 16:18
@gconnell this did get fixed when you moved to stenokeys.sh. Sorry took so long to close. :)

**Closed by dcode** 2017-02-14 16:18 UTC
Labels: bug
