### ISSUE TITLE
timedatectl fatal error in deploy_rock.sh

### ISSUE THREAD

**Issue by zcatbear** [rocknsm/rock#93] opened 2017-01-11 22:31 UTC
I get a fatal error when running `sudo ./deploy_rock.sh`. The ansible script does everything up until then just fine.   
When running just the ansible part with the `-vvv` option I get: 
```TASK [Set system timezone] *****************************************************
task path: /home/parallels/rock/ansible/rock.yml:211
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/commands/command.py
<simplerockbuild.simplerock.lan> ESTABLISH LOCAL CONNECTION FOR USER: root
<simplerockbuild.simplerock.lan> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1484173424.09-263622153399017 `" && echo ansible-tmp-1484173424.09-263622153399017="` echo $HOME/.ansible/tmp/ansible-tmp-1484173424.09-263622153399017 `" ) && sleep 0'
<simplerockbuild.simplerock.lan> PUT /tmp/tmpNgm1vB TO /root/.ansible/tmp/ansible-tmp-1484173424.09-263622153399017/command.py
<simplerockbuild.simplerock.lan> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1484173424.09-263622153399017/ /root/.ansible/tmp/ansible-tmp-1484173424.09-263622153399017/command.py && sleep 0'
<simplerockbuild.simplerock.lan> EXEC /bin/sh -c 'http_proxy='"'"''"'"' https_proxy='"'"''"'"' HTTP_PROXY='"'"''"'"' HTTPS_PROXY='"'"''"'"' /usr/bin/python /root/.ansible/tmp/ansible-tmp-1484173424.09-263622153399017/command.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1484173424.09-263622153399017/" > /dev/null 2>&1 && sleep 0'
fatal: [simplerockbuild.simplerock.lan]: FAILED! => {
    "changed": true, 
    "cmd": [
        "/usr/bin/timedatectl", 
        "set-timezone", 
        "UTC"
    ], 
    "delta": "0:00:00.018091", 
    "end": "2017-01-11 16:23:44.224104", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "_raw_params": "/usr/bin/timedatectl set-timezone UTC", 
            "_uses_shell": false, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }, 
        "module_name": "command"
    }, 
    "rc": 1, 
    "start": "2017-01-11 16:23:44.206013", 
    "stderr": "Failed to set time zone: Access denied", 
    "stdout": "", 
    "stdout_lines": [], 
    "warnings": []
}
	to retry, use: --limit @/home/parallels/rock/ansible/rock.retry

PLAY RECAP *********************************************************************
simplerockbuild.simplerock.lan : ok=19   changed=0    unreachable=0    failed=1   
```
My environment is as follows:
Parallels VM - Centos 7
Only two things I have installed are git and ansible

**Comment by zcatbear** [comment] 2017-01-11 22:35
After its failure I manually tried to change the data using `sudo timedatectl set-timezone UTC` and it changed the timezone. the `rock.yml` file has the line `when: anslbile_date_time.tz != "UTC"` so it shouldn't even be running once I set the time and date

**Comment by dcode** [comment] 2017-01-12 22:09
Hmmm....I tried to reproduce this, but wasn't able. 

Roughly, I did this:

1. Install from CentOS 7-1611 Minimal ISO
    a. Accepted defaults for everything
    b. Cleared partitions and gave CentOS the entire disk
    c. Created an `admin` user (check the box to make an administrator).
    d. Reboot upon installation complete.
2. `sudo ifup ens33; sudo yum install -y git epel-release`
3. `sudo yum install -y ansible`
4. `git clone https://github.com/rocknsm/rock.git`
5. `cd rock; git checkout devel; cd ansible`
6. `sudo ./generate_defaults.sh; sudo ./deploy_rock.sh`

Can you run the following and attach the output? This will list all SELinux denials.
```
sudo ausearch -m avc 
```

**Comment by zcatbear** [comment] 2017-01-12 22:15
```[parallels@centos-7-va ~]$ sudo ausearch -m avc
[sudo] password for parallels: 
----
time->Wed Jan 11 15:48:31 2017
type=SYSCALL msg=audit(1484171311.984:1390): arch=c000003e syscall=82 success=no exit=-13 a0=7f728d59ae10 a1=7f728d36515c a2=7f728d59ae00 a3=fffffffffffff3a9 items=0 ppid=1 pid=12464 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-timedat" exe="/usr/lib/systemd/systemd-timedated" subj=system_u:system_r:systemd_timedated_t:s0 key=(null)
type=AVC msg=audit(1484171311.984:1390): avc:  denied  { unlink } for  pid=12464 comm="systemd-timedat" name="localtime" dev="dm-0" ino=2490859 scontext=system_u:system_r:systemd_timedated_t:s0 tcontext=system_u:object_r:etc_t:s0 tclass=file
----
time->Wed Jan 11 15:49:03 2017
type=SYSCALL msg=audit(1484171343.448:1441): arch=c000003e syscall=82 success=no exit=-13 a0=7f9de6ad0e10 a1=7f9de5dec15c a2=7f9de6ad0e00 a3=fffffffffffff3a9 items=0 ppid=1 pid=13513 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-timedat" exe="/usr/lib/systemd/systemd-timedated" subj=system_u:system_r:systemd_timedated_t:s0 key=(null)
type=AVC msg=audit(1484171343.448:1441): avc:  denied  { unlink } for  pid=13513 comm="systemd-timedat" name="localtime" dev="dm-0" ino=2490859 scontext=system_u:system_r:systemd_timedated_t:s0 tcontext=system_u:object_r:etc_t:s0 tclass=file
----
time->Wed Jan 11 16:05:16 2017
type=SYSCALL msg=audit(1484172316.453:1658): arch=c000003e syscall=82 success=no exit=-13 a0=7fec47c2ce10 a1=7fec46fe215c a2=7fec47c2ce00 a3=fffffffffffff3a9 items=0 ppid=1 pid=18082 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-timedat" exe="/usr/lib/systemd/systemd-timedated" subj=system_u:system_r:systemd_timedated_t:s0 key=(null)
type=AVC msg=audit(1484172316.453:1658): avc:  denied  { unlink } for  pid=18082 comm="systemd-timedat" name="localtime" dev="dm-0" ino=2490859 scontext=system_u:system_r:systemd_timedated_t:s0 tcontext=system_u:object_r:etc_t:s0 tclass=file
----
time->Wed Jan 11 16:08:55 2017
type=SYSCALL msg=audit(1484172535.351:1672): arch=c000003e syscall=82 success=no exit=-13 a0=7fe4c42d1e10 a1=7fe4c3b4515c a2=7fe4c42d1e00 a3=fffffffffffff3a9 items=0 ppid=1 pid=19569 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-timedat" exe="/usr/lib/systemd/systemd-timedated" subj=system_u:system_r:systemd_timedated_t:s0 key=(null)
type=AVC msg=audit(1484172535.351:1672): avc:  denied  { unlink } for  pid=19569 comm="systemd-timedat" name="localtime" dev="dm-0" ino=2490859 scontext=system_u:system_r:systemd_timedated_t:s0 tcontext=system_u:object_r:etc_t:s0 tclass=file
----
time->Wed Jan 11 16:10:53 2017
type=SYSCALL msg=audit(1484172653.975:1692): arch=c000003e syscall=82 success=no exit=-13 a0=7fd6f1d34e70 a1=7fd6f0c8215c a2=7fd6f1d34e00 a3=fffffffc items=0 ppid=1 pid=20108 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-timedat" exe="/usr/lib/systemd/systemd-timedated" subj=system_u:system_r:systemd_timedated_t:s0 key=(null)
type=AVC msg=audit(1484172653.975:1692): avc:  denied  { unlink } for  pid=20108 comm="systemd-timedat" name="localtime" dev="dm-0" ino=2490859 scontext=system_u:system_r:systemd_timedated_t:s0 tcontext=system_u:object_r:etc_t:s0 tclass=file
----
time->Wed Jan 11 16:13:33 2017
type=SYSCALL msg=audit(1484172813.732:1705): arch=c000003e syscall=82 success=no exit=-13 a0=7f11f04e4e10 a1=7f11eff6e15c a2=7f11f04e4e00 a3=fffffffffffff3a9 items=0 ppid=1 pid=21821 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-timedat" exe="/usr/lib/systemd/systemd-timedated" subj=system_u:system_r:systemd_timedated_t:s0 key=(null)
type=AVC msg=audit(1484172813.732:1705): avc:  denied  { unlink } for  pid=21821 comm="systemd-timedat" name="localtime" dev="dm-0" ino=2490859 scontext=system_u:system_r:systemd_timedated_t:s0 tcontext=system_u:object_r:etc_t:s0 tclass=file
----
time->Wed Jan 11 16:23:01 2017
type=SYSCALL msg=audit(1484173381.349:1729): arch=c000003e syscall=82 success=no exit=-13 a0=7f2820d6ce10 a1=7f281f71015c a2=7f2820d6ce00 a3=fffffffffffff3a9 items=0 ppid=1 pid=24484 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-timedat" exe="/usr/lib/systemd/systemd-timedated" subj=system_u:system_r:systemd_timedated_t:s0 key=(null)
type=AVC msg=audit(1484173381.349:1729): avc:  denied  { unlink } for  pid=24484 comm="systemd-timedat" name="localtime" dev="dm-0" ino=2490859 scontext=system_u:system_r:systemd_timedated_t:s0 tcontext=system_u:object_r:etc_t:s0 tclass=file
----
time->Wed Jan 11 16:23:44 2017
type=SYSCALL msg=audit(1484173424.221:1746): arch=c000003e syscall=82 success=no exit=-13 a0=7f49d88d8e10 a1=7f49d6b9815c a2=7f49d88d8e00 a3=fffffffffffff3a9 items=0 ppid=1 pid=25495 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-timedat" exe="/usr/lib/systemd/systemd-timedated" subj=system_u:system_r:systemd_timedated_t:s0 key=(null)
type=AVC msg=audit(1484173424.221:1746): avc:  denied  { unlink } for  pid=25495 comm="systemd-timedat" name="localtime" dev="dm-0" ino=2490859 scontext=system_u:system_r:systemd_timedated_t:s0 tcontext=system_u:object_r:etc_t:s0 tclass=file
----
time->Wed Jan 11 16:29:55 2017
type=SYSCALL msg=audit(1484173795.167:1760): arch=c000003e syscall=82 success=no exit=-13 a0=7f9b167b9e10 a1=7f9b14a8f15c a2=7f9b167b9e00 a3=fffffffffffff3a9 items=0 ppid=1 pid=27415 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-timedat" exe="/usr/lib/systemd/systemd-timedated" subj=system_u:system_r:systemd_timedated_t:s0 key=(null)
type=AVC msg=audit(1484173795.167:1760): avc:  denied  { unlink } for  pid=27415 comm="systemd-timedat" name="localtime" dev="dm-0" ino=2490859 scontext=system_u:system_r:systemd_timedated_t:s0 tcontext=system_u:object_r:etc_t:s0 tclass=file```

**Comment by dcode** [comment] 2017-01-16 21:57
Did you find a resolution on this?

**Comment by zcatbear** [comment] 2017-01-16 21:59
No. I wasn't able to reproduce it either.

**Comment by dcode** [comment] 2017-02-14 16:17
Closing as invalid since the problem magically went away on clean install.

**Closed by dcode** 2017-02-14 16:17 UTC
Labels: invalid
